name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  cargo_tests:
    name: ${{ matrix.os }} ${{ matrix.rust_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        rust_channel: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust_channel }}
    - run: cargo test
    - run: cargo +nightly update -Zminimal-versions
    - run: cargo test
